version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  generador:
    build:
      context: ./generador
      dockerfile: Dockerfile
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  cache:
    build:
      context: ./cache
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - generador

volumes:
  mongo-data:
